site_name: ComputerScience
pages:
- "Home": 'index.md'
- "Data Structure & ALgorithm": 'data_algorithm.md'
- "Database":
  - "Introduction": "database.md"
  - "SQL": "db_sql.md"
  - "MySQL": "db_mysql.md"
  - "Redis": "db_redis.md"
- "Networking": 'networking.md'
- "OOP":
  - "Introduction": 'oop.md'
  - "UML": 'oop_uml.md'
- "Operating System": 'os.md'
markdown_extensions:
    - footnotes
